### ISSUE TITLE
Document modules, functions, classes

### ISSUE THREAD

**Issue by ruzv** [testdevlab/Py-TestUI#32]
Currently, all `pylint` checks for missing documentation are disabled or in case they were reenabled vscode will underline almost all functions and methods. Would be nice if these checks didn't fail and could be reenabled. This could be achieved as a step-by-step process where when some part of PyTestUI requires changes additionally to doing the required changes the surrounding methods/functions and classes could be documented.

**Comment by alvarolaserna** [comment]
Yes, we are starting to work to add more documented methods and modules. We will also introduce github actions to check this things, as well as we will add test pipelines to it
