### ISSUE TITLE
Update PyTestUI installation section on Readme

### ISSUE THREAD

**Issue by iEnergyy** [testdevlab/Py-TestUI#43]
It says: **Py-TestUI can be installed via pip** pip3 install git+https://github.com/testdevlab/Py-TestUI@v1.0.6 but if I try to install v1.0.6 it will error. I had to change it to pip3 install git+https://github.com/testdevlab/Py-TestUI@v1.1.1 to install it.

**Comment by ruzv** [comment]
can you share the error you got?

**Comment by iEnergyy** [comment]
![image](https://user-images.githubusercontent.com/44242768/195866430-0e3cce79-d667-4be1-a18c-7ce788ea1528.png)

**Comment by ruzv** [comment]
try installing it with pip
https://pypi.org/project/python-testui/

**Comment by alvarolaserna** [comment]
If there are no further comments I will close this issue and mark it as resolved

**Comment by alvarolaserna** [comment]
closed as it seems to be resolved, will reopen if relevant
