### ISSUE TITLE
Logs in source files

### ISSUE THREAD

**Issue by ruzv** [testdevlab/Py-TestUI#48]
`testui/support/logger.py` uses `__file__` to determine the location of log files. This is fine as long as the user owns the whole source tree. But in case pytestui is installed globally, then log files are attempted to be created in a root-owned, shared by whole system directories, basically littering in the system, if the runner has sufficient permission, if not then the user is simply unable to run any tests as pytestui run as a non-root user will attempt to create log files in root owned dirs which results in a permissions error, making the lib unusable.

**Comment by alvarolaserna** [comment]
Yes, I see the problem, I have created a branch to resolve this issue, it is attached to the Development @ruzv
